# -*- coding: utf-8 -*-
"""Assignment_1 (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fM52xWpfQu8--svs6I18zLubNbFSWa5K

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s = "Hi there Sam!"
a=s.split()
a

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

planet="Earth"
diameter=12742
print(f"the diameter of {planet} is {diameter} Kilometers.")

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np
np.zeros(10)

import numpy as np
a=np.ones(10)*5
print(a)

"""## 5. Create an array of all the even integers from 20 to 35"""

import numpy as np
a=np.arange(20,35)
b=(a%2==0)
c=a[b]
print(c)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr=np.concatenate((a,b))
print(arr)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

import pandas as pd
lists = [['sam', 22], ['ravi', 25], ['kumar', 24]]
df=pd.DataFrame(lists,columns=['name','age'],dtype=int)
print(df)

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

from datetime import date,timedelta
sdate=date(2023,1,1)
edate=date(2023,2,10)
delta=edate-sdate
for i in range(delta.days+1):
 day=sdate+timedelta(days=i)
 print(day)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['sno','name','mark'],dtype=int)
print(df)